name: Release
on:
  push:
    branches: [ master, staging ]

jobs:
  release:
    runs-on: ubuntu-latest

    env:
      GIT_AUTHOR_NAME: Joseph R Miles
      GIT_AUTHOR_EMAIL: joe@jrm.dev

    name: Run Semantic Release
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: 15.x

      - run: npm ci

      - run: npx semantic-release --dry-run
        env:
          GITHUB_NPM_CONFIG_REGISTRY: https://npm.pkg.github.com/
          GITHUB_NPM_TOKEN: ${{ secrets.GH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          PUBLIC_NPM_CONFIG_REGISTRY: https://registry.npmjs.org/
          PUBLIC_NPM_TOKEN: ${{ secrets.NPM_TOKEN }}